apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage-pvc-encrypt
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-hdd-encrypt
  resources:
    requests:
      storage: 1Gi