apiVersion: hwameistor.io/v1alpha1
kind: LocalDiskClaim
metadata:
  name: node-1
  namespace: kube-system
spec:
  owner: local-storage   # localstoragenode 名称
  nodeName: k8s-node1
  description:
    diskType: HDD   # 磁盘种类
