apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hwameistor-storage-disk-hdd
parameters:
  diskType: HDD
provisioner: disk.hwameistor.io
allowVolumeExpansion: false
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer