apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hwameistor-disk-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hwameistor-storage-disk-hdd

